apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hhm-api-runtime
  namespace: hhm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: hhm-api-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: hhm/prod/api-runtime
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hhm-web-runtime
  namespace: hhm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: hhm-web-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: hhm/prod/user-web-runtime
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hhm-ghcr-pull
  namespace: hhm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: hhm-ghcr-pull
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: hhm/prod/ghcr-pull
        property: dockerconfigjson
