apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hhm-public-tunnel-token
  namespace: hhm-edge
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: hhm-public-tunnel-token
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: hhm/prod/cloudflare/public-tunnel
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hhm-admin-tunnel-token
  namespace: hhm-edge
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: hhm-admin-tunnel-token
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: hhm/prod/cloudflare/admin-tunnel
